use Anshushop;

                          -- Section 1 — Basic Data Exploration

-- =========================================================
-- 1. BASIC DATA EXPLORATION
-- =========================================================

-- Finding: Counts the total number of customers in the database.
-- Business Use: Provides an overview of the customer base.

SELECT COUNT(*) AS total_customers
FROM customers;


-- Finding: Counts the total number of products available.
-- Business Use: Shows the size of the product catalog.

SELECT COUNT(*) AS total_products
FROM products;


-- Finding: Counts the total number of orders.
-- Business Use: Provides an overview of overall order activity.

SELECT COUNT(*) AS total_orders
FROM orders;


-- Finding: Displays the number of orders for each order status.
-- Business Use: Helps understand the distribution of Delivered,
-- Pending, and Cancelled orders.

SELECT 
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;

                 -- =========================================================
                             -- 2. CUSTOMER ANALYSIS
-- =========================================================

-- Finding: Shows the number of orders placed by each customer.
-- Business Use: Identifies customers with high and low purchase activity.

SELECT 
    c.name,
    COUNT(o.order_id) AS total_orders
FROM customers c
LEFT JOIN orders o 
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.name
ORDER BY total_orders DESC;


-- Finding: Calculates the total amount spent by each customer.
-- Business Use: Identifies high-value customers.

SELECT 
    c.name,
    SUM(p.amount) AS total_spent
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN payments p 
    ON o.order_id = p.order_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC;

                        -- =========================================================
                               -- 3. PRODUCT ANALYSIS
                        -- =========================================================

-- Finding: Calculates the total quantity sold for each product.
-- Business Use: Identifies the best-selling products.

SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
GROUP BY p.product_id, p.product_name
ORDER BY total_sold DESC;


-- Finding: Calculates revenue generated by each product
-- from Delivered orders only.
-- Business Use: Identifies the products contributing the most revenue.

SELECT 
    p.product_name,
    SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p 
    ON oi.product_id = p.product_id
JOIN orders o 
    ON oi.order_id = o.order_id
WHERE o.order_status = 'Delivered'
GROUP BY p.product_id, p.product_name
ORDER BY revenue DESC;


-- Finding: Displays products with their current stock levels.
-- Business Use: Helps identify products that may require restocking.

SELECT 
    product_name,
    category,
    stock
FROM products
ORDER BY stock ASC;

                    -- =========================================================
                                  -- 4. ORDER ANALYSIS
-- =========================================================

-- Finding: Counts orders based on their current status.
-- Business Use: Helps monitor successful, pending, and cancelled orders.

SELECT 
    order_status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY order_status;


-- Finding: Counts the total number of cancelled orders.
-- Business Use: Helps monitor order cancellation levels.

SELECT COUNT(*) AS cancelled_orders
FROM orders
WHERE order_status = 'Cancelled';


-- Finding: Shows the number of orders placed on each date.
-- Business Use: Helps identify daily order trends.

SELECT 
    order_date,
    COUNT(*) AS daily_orders
FROM orders
GROUP BY order_date
ORDER BY order_date;

                     -- =========================================================
                                 -- 5. REVENUE ANALYSIS
-- =========================================================

-- Finding: Calculates the total revenue recorded in payments.
-- Business Use: Provides the overall revenue generated.

SELECT 
    SUM(amount) AS total_revenue
FROM payments;


-- Finding: Calculates the average payment amount.
-- Business Use: Helps estimate the average transaction value.

SELECT 
    AVG(amount) AS average_transaction_value
FROM payments;


-- Finding: Calculates revenue generated through each payment mode.
-- Business Use: Shows which payment methods contribute the most revenue.

SELECT 
    payment_mode,
    SUM(amount) AS revenue
FROM payments
GROUP BY payment_mode
ORDER BY revenue DESC;

                      -- =========================================================
                               -- 6. PAYMENT ANALYSIS
-- =========================================================

-- Finding: Counts the number of transactions for each payment mode.
-- Business Use: Helps understand customer payment preferences.

SELECT 
    payment_mode,
    COUNT(*) AS transaction_count
FROM payments
GROUP BY payment_mode
ORDER BY transaction_count DESC;


-- Finding: Calculates the average transaction amount
-- for each payment mode.
-- Business Use: Helps compare transaction values across payment methods.

SELECT 
    payment_mode,
    AVG(amount) AS average_transaction_value
FROM payments
GROUP BY payment_mode
ORDER BY average_transaction_value DESC;

                             -- =========================================================
								  -- 7. JOIN QUERIES
-- =========================================================

-- Finding: Combines customers and orders to show
-- which customer placed each order.
-- Business Use: Connects customer information with order activity.

SELECT 
    c.name,
    o.order_id,
    o.order_date,
    o.order_status
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
ORDER BY o.order_date;


-- Finding: Combines orders, order items, and products
-- to show the products purchased in each order.
-- Business Use: Provides order-level product details.

SELECT 
    o.order_id,
    p.product_name,
    oi.quantity,
    p.price
FROM orders o
JOIN order_items oi 
    ON o.order_id = oi.order_id
JOIN products p 
    ON oi.product_id = p.product_id
ORDER BY o.order_id;


-- Finding: Combines customers, orders, and payments
-- to calculate customer spending.
-- Business Use: Identifies high-value customers.

SELECT 
    c.name,
    SUM(pay.amount) AS total_spent
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN payments pay 
    ON o.order_id = pay.order_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC;

                       -- =========================================================
                                   -- 8. ADVANCED SQL QUERIES
-- =========================================================

-- Finding: Categorizes customers based on their total spending.
-- Business Use: Helps segment customers into different value groups.

SELECT 
    c.name,
    SUM(p.amount) AS total_spent,
    CASE
        WHEN SUM(p.amount) >= 2000 THEN 'High Value'
        WHEN SUM(p.amount) >= 1000 THEN 'Medium Value'
        ELSE 'Low Value'
    END AS customer_segment
FROM customers c
JOIN orders o 
    ON c.customer_id = o.customer_id
JOIN payments p 
    ON o.order_id = p.order_id
GROUP BY c.customer_id, c.name
ORDER BY total_spent DESC;

                       -- =========================================================
                                  -- 9. BUSINESS INSIGHTS
-- =========================================================

-- Insight 1:
-- Identify the products generating the highest revenue.
-- This can help the business prioritize high-performing products.

-- Insight 2:
-- Identify high-value customers based on total spending.
-- These customers can be targeted with loyalty programs and
-- personalized offers.

-- Insight 3:
-- Analyze cancelled orders to monitor potential customer
-- experience or fulfillment issues.

-- Insight 4:
-- Compare payment modes to understand customer payment
-- preferences.

-- Insight 5:
-- Analyze product stock levels to identify products that
-- may require restocking.
                 
